apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
data:
{{ if .Values.datasources }}
{{ toYaml .Values.datasources | nindent 2 }}
{{ else }}
  datasources.yaml: |-
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      url: "{{ .Values.mimirurl }}/prometheus" # Change this to your Prometheus service address
      access: proxy
      isDefault: true
{{ end }}
{{ toYaml .Values.providers | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-red-metrics-classic-dashboard
data:
  grafana-dashboard-red-metrics-classic.json: |
{{ .Files.Get "conf/grafana-dashboard-red-metrics-classic.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-red-metrics-native-dashboard
data:
  grafana-dashboard-red-metrics-native.json: |
{{ .Files.Get "conf/grafana-dashboard-red-metrics-native.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-jvm-metrics-dashboard
data:
  grafana-dashboard-jvm-metrics.json: |
{{ .Files.Get "conf/grafana-dashboard-jvm-metrics.json" | indent 4 }}
