apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grafana.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "{{ .Values.adminUser }}"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "{{ .Values.adminPassword }}"
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
            - name: config
              mountPath: /etc/grafana/provisioning/dashboards/providers.yaml
              subPath: providers.yaml
            - name: red-metrics-classic-dashboard
              mountPath: /otel-lgtm/grafana-dashboard-red-metrics-classic.json
              subPath: grafana-dashboard-red-metrics-classic.json
            - name: red-metrics-native-dashboard
              mountPath: /otel-lgtm/grafana-dashboard-red-metrics-native.json
              subPath: grafana-dashboard-red-metrics-native.json
            - name: jvm-metrics-dashboard
              mountPath: /otel-lgtm/grafana-dashboard-jvm-metrics.json
              subPath: grafana-dashboard-jvm-metrics.json
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana.fullname" . }}-config
        - name: red-metrics-classic-dashboard
          configMap:
            name: {{ include "grafana.fullname" . }}-red-metrics-classic-dashboard
        - name: red-metrics-native-dashboard
          configMap:
            name: {{ include "grafana.fullname" . }}-red-metrics-native-dashboard
        - name: jvm-metrics-dashboard
          configMap:
            name: {{ include "grafana.fullname" . }}-jvm-metrics-dashboard
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
