{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ include "grafana.fullname" . }}  # The name of the Grafana service
  port:
    targetPort: 3000  # Port that Grafana service is exposing
  host: {{ .Values.route.host }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
