apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    app: {{ include "otel-collector.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "otel-collector.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "otel-collector.name" . }}
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $index, $port := .Values.ports }}
            - name: {{ $port.name | default (printf "port-%d" $index) }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.protocol | default "TCP" }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/otel_collector_config.yaml
              subPath: otel_collector_config.yaml
            - name: tls-secret
              mountPath: /etc/tls-secret
          args: [ "--config", "/etc/otel_collector_config.yaml" ,
                  "--feature-gates", "-component.UseLocalHostAsDefaultHost" ]
      volumes:
        - name: tls-secret
          secret:
            name: otel-collector-tls
        - name: config
          configMap:
            name: {{ include "otel-collector.fullname" . }}-config
