---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: otel-collector-tls-es
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: otel-collector-tls
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: {{ .Values.route.tlsSecretKeyName }}
