{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "otel-collector.name" . }}
  labels:
    app: {{ include "otel-collector.name" . }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-otel-collector-loadbalancer
    weight: 100
  port:
    targetPort: 4317
  host: {{ .Values.route.host | default "" }}
  path: {{ .Values.route.path }}
  tls:
    termination: {{ .Values.route.tlsTermination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}

{{- end }}
